pull_request_rules:
  - name: automatic merge when CI passes and reviewed
    conditions:
      - "#approved-reviews-by>=2"
      - status-success=lint-check
      - base=master
      - label=ready-to-merge  # only auto-merge when PR with this label
    actions:
      merge:
        method: merge
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}