---
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev:  "v1.13.1"
    hooks:
      - id: helm-docs-container
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=stable
