{{- $externalDb := .Values.global.externalDatabase }}
{{- $dc := .Values.global.datacube }}
{{- $index := .Values.index }}
{{- $image := .Values.global.image }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $index.jobname }}"
  labels:
    heritage: {{ $index.jobname }}
    release: {{ $index.jobname }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: index
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{ $index.jobname }}"
      labels:
        heritage: {{ $index.jobname }}
        release: {{ $index.jobname }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
{{ toYaml $index.annotations | indent 8 }}
    spec:
      initContainers:
      - name: postgres-listener
        image: alpine
        command: ["sh", "-c", "for i in $(seq 1 200); do nc -z -w3 {{ $externalDb.host }} {{ $externalDb.port }} && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name: datacube-index
        image: "{{ $image.repository }}:{{ $image.tag }}"
        imagePullPolicy: {{ $image.pullPolicy }}
        args: [ {{- range $index.dockerArgs }} {{ . | quote }}, {{ end -}} ]
        resources:
{{ toYaml $index.resources | indent 10 }}
        env:
        - name: WMS_CONFIG_URL
{{- if $index.wmsConfigURL }}
          value: {{ $index.wmsConfigURL | quote }}
{{- else }}
          value: {{ $dc.wmsConfigURL | quote }}
{{- end }}
{{- if $index.products }}
        - name: PRODUCT_URLS
          value: {{ template "helm-toolkit.utils.joinListWithSpace" $index.products }}
{{- else if $dc.products}}
        - name: PRODUCT_URLS
          value: {{ template "helm-toolkit.utils.joinListWithSpace" $dc.products }}
{{- end }}
{{- if $index.product_ranges }}
        - name: DC_RANGES_PRODUCT
          value: {{ $index.product_ranges | quote }}
{{- end }}
        - name: DC_S3_INDEX_BUCKET
          value: {{ $index.bucket | quote }}
        - name: DC_S3_INDEX_PREFIX
          value: {{ template "helm-toolkit.utils.joinListWithSpace" $index.prefix }}
        - name: DC_S3_INDEX_SUFFIX
          value: {{ $index.suffix | quote }}
        - name: DB_HOSTNAME
          value: {{ $externalDb.host | quote }}
        - name: DB_PORT
          value: {{ $externalDb.port | quote }}
        - name: DB_DATABASE
          value: {{ $externalDb.database | quote }}
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ $externalDb.database }}
              key: postgres-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $externalDb.database }}
              key: postgres-password
{{- if $index.additionalEnvironmentVars }}
{{- range $arg, $value := $index.additionalEnvironmentVars }}
        - name: {{ $arg | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
      restartPolicy: Never
