{{- if not .Values.adaptive.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "datacube-dask.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "datacube-dask.name" . }}
    helm.sh/chart: {{ include "datacube-dask.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "datacube-dask.fullname" . }}-worker
  minReplicas: {{ .Values.worker.minReplicas }}
  maxReplicas: {{ .Values.worker.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.worker.targetCpu }}
{{- end }}
