apiVersion: v1
description: A Helm chart for Datacube Explorer
name: datacube-explorer
version: 0.5.32
# renovate: docker=ghcr.io/opendatacube/explorer
appVersion: 1.0.0
keywords:
- datacube
- http
- web
- application
- python
- stac
home: https://www.opendatacube.org/documentation
maintainers:
 - name: DEA Teams
   email: deacloudteam@ga.gov.au
sources:
  - https://github.com/opendatacube/explorer
  - https://github.com/opendatacube/datacube--charts
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/opendatacube/datacube-charts
    - name: Upstream Project
      url: https://github.com/opendatacube/explorer
