{{- if .Values.ows.enabled }}
{{- if .Values.ows.hpa.autoscaling }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "datacube-ows.fullname" . }}
  labels:
    app: {{ template "datacube-ows.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ template "datacube-ows.fullname" . }}-{{ .Values.clusterInfo.envName }}"
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
{{ toYaml .Values.ows.hpa.metrics | indent 10 }}

{{- end }}
{{- end }}