{{- if .Values.ows.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "datacube-ows.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "datacube-ows.fullname" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "80"
    port: {{ .Values.ows.externalPort }}
    targetPort: {{ .Values.ows.internalPort }}
  selector:
    app: {{ template "datacube-ows.name" . }}
    release: {{ .Release.Name }}
{{- end }}
