{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "datacube-ows.fullname" . }}
  labels:
    app: {{ template "datacube-ows.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{- if .Values.database.username }}
  postgres-username: {{ .Values.database.username | b64enc | quote }}
  {{ else }}
  postgres-username: {{ .Release.Name | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  postgres-password:  {{ .Values.database.password | b64enc | quote }}
  {{ else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}