replicaCount: 1

database:
  database: datacube
  host: localhost
  port: 5432
  # existingSecret: datacube
  existingSecret: ows-reader

aws:
  existingSecret: ows-wps-aws

clusterInfo:
  envName: dev

image:
  # Docker Hub: https://hub.docker.com/r/opendatacube/wps
  # Source Repository: https://github.com/opendatacube/datacube-wps
  registry: 538673716275.dkr.ecr.ap-southeast-2.amazonaws.com
  repository: opendatacube/wps
  tag: "0.4.1-3-ga2262d2"
  pullPolicy: IfNotPresent
#    database:
#      database: ${db_name}
#      host: ${db_hostname}
#      existingSecret: ${db_secret}
clusterInfo:
  envName: dev
wps:
  enabled: true
  baseurl: ""
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1
      memory: 600Mi
#      Injected by Flux - using secrets
#      baseurl: "https://ows.${domain_name}/wps/"
#      annotations:
#        iam.amazonaws.com/role: ${role_name}
  additionalEnvironmentVars:
    APPLICATION_ROOT: /
    SCRIPT_NAME: /
    prometheus_multiproc_dir: "/dev/shm"
    # SENTRY_PROJECT: "2396014"
    # SENTRY_KEY: "fd4798d6f0bd47598b990a0b036d2cf6"
    # AWS_DEFAULT_REGION: "ap-southeast-2"
  readinessProbe:
    exec:
      command:
      - "/bin/sh"
      - "-c"
      - "curl --silent 'http://localhost:8000/wps/?service=WPS&request=getcapabilities&version=1.0.0'"
    initialDelaySeconds: 30
    periodSeconds: 30
  livenessProbe:
    exec:
      command:
      - "/bin/sh"
      - "-c"
      - "curl --silent 'http://localhost:8000/wps/ping'"
    periodSeconds: 30
    # targetCpu: 10

wpsConfig:
  image: { }

hpa:
  enabled: true
  minimum_replica_count: 1
  maximum_replica_count: 5
  cpu:
    target_utilization_percentage: 70

ingress:
  enabled: true
  path: "/wps/*"
  hosts:
  - wps-mike.dev.dea.ga.gov.au
#      Injected by Flux - using secrets
#      hosts:
#        - ows.${domain_name}
  annotations:
    kubernetes.io/ingress.class: merge
    merge.ingress.kubernetes.io/config: merged-ingress-external
    merge.ingress.kubernetes.io/priority: "1"

service:
  type: NodePort
  port: 8000
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/wps/ping"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "60"
    alb.ingress.kubernetes.io/target-group-attributes: "load_balancing.algorithm.type=least_outstanding_requests"
