# Default values for datacube-wms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: docker.io
  repository: opendatacube/wps
  tag: 'latest'
  pullPolicy: Always

database:
  database: datacube
  host: localhost
  port: 5432
  # existingSecret: datacube
  existingSecret: ows-reader

aws:
  existingSecret: ows-wps-aws

clusterInfo:
  envName: dev

##
## Datacube WPS configuration
##
wps:
  enabled: true
  baseurl: ""
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
  targetCpu: 10
  autoscaling:
    enabled: True
    minimum_replica_count: 1
    maximum_replica_count: 2
    cpu:
      target_utilization_percentage: 70
  annotations: { }
  additionalEnvironmentVars: { }
  livenessProbe:
    exec:
      command:
      - "/bin/sh"
      - "-c"
      - "curl --silent 'http://localhost:8000/?service=WPS&request=GetCapabilities&version=1.0.0'"
    initialDelaySeconds: 30
    periodSeconds: 30
  readinessProbe: {}
wpsConfig:
  image: { }

affinity: {}

ingress:
  enabled: false
  prefixes: [ ]
  domain: ""

service:
  type: NodePort
  port: 8000


fullnameOverride: ""
