apiVersion: v2
type: application
name: datacube-ows
description: Datacube Web Map Service
version: 0.21.0
# renovate: docker=ghcr.io/opendatacube/ows
appVersion: 1.0.0
keywords:
  - datacube
  - http
  - web
  - application
  - python
home: https://www.opendatacube.org/documentation
sources:
  - https://github.com/opendatacube/datacube-charts
  - https://github.com/opendatacube/datacube-core
  - https://github.com/opendatacube/datacube-ows
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/opendatacube/datacube-charts
    - name: Upstream Project
      url: https://github.com/opendatacube/datacube-ows
