apiVersion: v2
type: application
name: datacube-index
description: Datacube OGC Web Services Indexing
version: 0.5.0
# renovate: docker=docker.io/opendatacube/ows
appVersion: 1.0.0
keywords:
  - datacube
  - http
  - web
  - application
  - python
  - index
  - archive
home: https://www.opendatacube.org/documentation
sources:
  - https://github.com/opendatacube/datacube-charts
  - https://github.com/opendatacube/datacube-core
  - https://github.com/opendatacube/datacube-ows
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/opendatacube/datacube-charts
