{{- if not (empty .Values.additionalSettings) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datacube-explorer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "datacube-explorer.name" . }}
    helm.sh/chart: {{ include "datacube-explorer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  settings.env.py: {{ .Values.additionalSettings | quote }}
{{- end }}
