name: Publish charts

on:
  push:
    branches:
      - master

env:
  REPO : "https://opendatacube.github.io/datacube-charts/charts"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - name: Package charts into a tarball
      run: |
        git remote set-branches --add origin gh-pages-test
        git checkout origin/gh-pages-test -- charts/
        bash deploy-charts.sh $REPO stable

    - name: Publish charts to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./charts
        publish_branch: gh-pages
        destination_dir: ./charts
        keep_files: true
        commit_message: "deployed charts for"