name: Publish charts

on:
  push:
    branches:
      - update-readme

env:
  REPO : "https://opendatacube.github.io/datacube-charts/charts/"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: deploy
      uses: J12934/helm-gh-pages-action@master
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        deploy-branch: gh-pages-test
        charts-folder: stable
