name: Publish charts

on:
  push:
    branches:
      - update-readme

env:
  REPO : "https://opendatacube.github.io/datacube-charts/charts/"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - name: Package charts into a tarball
      run: |
        git remote set-branches --add origin gh-pages-test
        git checkout origin/gh-pages-test -- charts/
        bash deploy-charts.sh $REPO stable

    - name: Package charts into a tarball
      run: |
        git remote set-branches --add origin gh-pages
        git checkout origin/gh-pages -- charts/
        bash deploy-charts.sh $REPO stable

    - name: Publish charts to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages-test
        CLEAN: false

#    - name: Release chart (index.yml)
#      uses: J12934/helm-gh-pages-action@master
#      with:
#        access-token: ${{ secrets.ACCESS_TOKEN }}
#        deploy-branch: gh-pages-test
#        charts-folder: stable
